"""user model defaults

Revision ID: e98a57276c43
Revises: 6387eff837e1
Create Date: 2023-12-06 23:40:27.477388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98a57276c43'
down_revision: Union[str, None] = '6387eff837e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role', existing_type=sa.String(), server_default=sa.text("'user'"))
    op.alter_column('users', 'disabled', existing_type=sa.Boolean(), server_default="false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
